name: Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        board: [esp-box, esp32s3_korvo_2, esp32s3_others, linux]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build
      run: |
        docker run -v $PWD:/project -w /project -u 0 \
        -e HOME=/tmp -e WIFI_SSID=A -e WIFI_PASSWORD=B -e OPENAI_API_KEY=X \
        espressif/idf:latest \
        /bin/bash -c 'idf.py @boards/${{ matrix.board }}.cfg build'
      shell: bash
